[package]
name = "zk_coprocessor_contracts"
type = "contract"
version = "0.1.0"
authors = ["zk-coprocessor-bridge"]
compiler_version = ">=0.27.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v2.0.2", directory = "noir-projects/aztec-nr/aztec" }
