version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }

  - package-ecosystem: "npm"
    directory: "/apps"
    schedule: { interval: "weekly" }

  - package-ecosystem: "cargo"
    directory: "/solana-program"
    schedule: { interval: "weekly" }

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule: { interval: "weekly" }
