# Runs builds for Solana/Anchor, EVM/Foundry, Aztec/Noir, and TypeScript apps.

name: CI
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Toolchains (system libs, Solana CLI, Anchor avm)
      - name: Setup toolchains
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config libudev-dev llvm libclang-dev protobuf-compiler libssl-dev curl jq tar rustc cargo
          curl -sSfL https://solana-install.solana.workers.dev | bash
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
          # enable Solana in this step too
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          cargo install --git https://github.com/coral-xyz/anchor avm --locked
          avm install latest && avm use latest
          anchor --version

      # Foundry (official action avoids PATH issues)
      - name: Foundry toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with: { version: stable }

      # Aztec CLI (provides `aztec nargo` and `aztec postprocess-contract`)
      - name: Aztec CLI
        run: |
          curl -s https://install.aztec.network | bash
          echo "$HOME/.aztec/bin" >> "$GITHUB_PATH"
          export PATH="$HOME/.aztec/bin:$PATH"
          aztec --version

      # Solana: anchor build
      - name: Anchor build
        working-directory: solana-program
        run: anchor build

      # EVM: forge build
      - name: Foundry build
        working-directory: evm-contracts
        run: forge build

      # Aztec/Noir: compile + postprocess
      - name: Aztec compile & postprocess
        working-directory: aztec-contracts/contracts/zk-coprocessor-contracts
        run: |
          aztec-nargo compile
          aztec-postprocess-contract

      # TypeScript (no npm ci per your request)
      - name: TypeScript build
        uses: actions/setup-node@v5
        with: { node-version: 24 }
      - name: Build apps
        working-directory: apps
        run: npm run build
